Add endpoint to fetch filters in JSON format
python-discord/site pull request #1166
Opened 2023-12-10 17:24 UTC by jchristgit

While this is an API endpoint consumed by the bot, keep it in the `resources` app instead of the `api` app, as all the logic and data for resources is contained within the `resources` app and we don't want to start messing around with that.

The response format from the endpoint is as follows:

    {
      "filters": {
        "Difficulty": {
          "filters": [
            "Beginner",
            "Intermediate"
          ],
          "icon": "fas fa-brain",
          "hidden": false
        },
        "Type": {
          "filters": [
            "Book",
            "Community",
            "Course",
            "Interactive",
            "Podcast",
            "Project Ideas",
            "Tool",
            "Tutorial",
            "Video"
          ],
          "icon": "fas fa-photo-video",
          "hidden": false
        },
        "Payment tiers": {
          "filters": [
            "Free",
            "Paid",
            "Subscription"
          ],
          "icon": "fas fa-dollar-sign",
          "hidden": true
        },
        "Topics": {
          "filters": [
            "Algorithms and Data Structures",
            "Data Science",
            "Databases",
            "Discord Bots",
            "Game Development",
            "General",
            "Microcontrollers",
            "Security",
            "Software Design",
            "Testing",
            "Tooling",
            "User Interface",
            "Web Development",
            "Other"
          ],
          "icon": "fas fa-lightbulb",
          "hidden": true
        }
      },
      "valid_filters": {
        "topics": [
          "algorithms-and-data-structures",
          "data-science",
          "databases",
          "discord-bots",
          "game-development",
          "general",
          "microcontrollers",
          "security",
          "software-design",
          "testing",
          "tooling",
          "user-interface",
          "web-development",
          "other"
        ],
        "payment_tiers": [
          "free",
          "paid",
          "subscription"
        ],
        "type": [
          "book",
          "community",
          "course",
          "interactive",
          "podcast",
          "project-ideas",
          "tool",
          "tutorial",
          "video"
        ],
        "difficulty": [
          "beginner",
          "intermediate"
        ]
      }
    }

Closes #710.

2023-12-11 17:14 UTC, ChrisLovering approved these changes

2023-12-31 14:56 UTC, wookie184 requested changes
The response format here doesn't seem ideal. My understanding is that "filters" is the display name, and "valid_filters" is what goes in the URL(?), but the response doesn't link these together.

We could link them together in the structure, along the lines of this:
```
[
    {
      "name": "Difficulty",
      "url_value": "difficulty",
      "options": [
        {"name": "Beginner", "url_value": "beginner"},
        ...
      ],
      "icon": "fas fa-brain",
      "hidden": false,
    },
    ...
]
```

Alternatively we could maybe just drop the "valid_filters" section and document the transformation to get from the name to the url.

2024-06-14 16:57 UTC, jchristgit commented
@wookie184 thanks for the review and sorry for the long delay. I've updated the response format, the "sluggified" / "kebabified" version of the names can now be found in the `slug` field for the respective category, and the `filter_slugs` field for each filter. To be specific, `filter_slugs[3] == to_kebabcase(slugs[3])`. Let me know what you think.

2024-07-18 20:45 UTC, wookie184 requested changes
This seems to undo the fix for https://github.com/python-discord/site/issues/1209, I think it will cause performance issues.

2024-08-02 14:12 UTC, jchristgit commented
Looks like I managed to mess up during rebasing. It should all be fine now, and the code should be a lot simpler thanks to Rohan's changes. Please also see the new response file format.

2025-02-01 10:33 UTC, jchristgit commented
Would be happy for a re-review here, in loving memory of our brother Chris.

2025-03-02 12:52 UTC, wookie184 approved these changes
Not tested but LGTM

2025-03-02 13:51 UTC, merged