Significantly refactor the timeline CSS implementation
python-discord/site pull request #1262
Opened 2024-03-19 13:34 UTC by hedyhli

Description WIP

2024-03-25 18:37 UTC, wookie184 requested changes
Other than launching us 1000 years into the future, this looks great!

2024-03-25 18:37 UTC, wookie184 commented on pydis_site/templates/home/timeline.html
> +          <h3>Summer Code Jam 3033 (CJ9)</h3>
```suggestion
          <h3>Summer Code Jam 2022 (CJ9)</h3>
```
:P

2024-03-25 18:37 UTC, wookie184 commented on pydis_site/templates/home/timeline.html
> +          <h3>Summer Code Jam 3031 (CJ8)</h3>
```suggestion
          <h3>Summer Code Jam 2021 (CJ8)</h3>
```

2024-03-25 18:37 UTC, wookie184 commented on pydis_site/templates/home/timeline.html
> +          <h3>Summer Code Jam 3030 Highlights</h3>
```suggestion
          <h3>Summer Code Jam 2020 Highlights</h3>
```

2024-03-25 18:37 UTC, wookie184 commented on pydis_site/templates/home/timeline.html
> +          <h3>Python Discord hosts the 3030 CPython Core Developer Q&A</h3>
```suggestion
          <h3>Python Discord hosts the 2020 CPython Core Developer Q&A</h3>
```

2024-03-25 18:37 UTC, wookie184 commented on pydis_site/templates/home/timeline.html
> +          <h3>PyDis summer code jam 3030 with the theme “Early Internet” and Django as the technology</h3>
```suggestion
          <h3>PyDis summer code jam 2020 with the theme “Early Internet” and Django as the technology</h3>
```

2024-03-25 18:37 UTC, wookie184 commented on pydis_site/templates/home/timeline.html
> +          <h3>PyDis Game Jam 3030 with the “Three of a Kind” theme and Arcade as the technology</h3>
```suggestion
          <h3>PyDis Game Jam 2020 with the “Three of a Kind” theme and Arcade as the technology</h3>
```

2024-03-25 23:54 UTC, hedyhli commented
@wookie184 that's awful! I was too careless with my inline substitutions. I'll fix it right away, thank you.

2024-03-26 12:54 UTC, wookie184 approved these changes
🥇

2024-03-29 10:28 UTC, jchristgit approved these changes
Thank you!

2024-03-29 10:44 UTC, merged