Fetch timeline entries from Markdown files with YAML frontmatter
python-discord/site pull request #1293
Opened 2024-04-06 04:59 UTC by hedyhli

- The rest of the existing entries are yet to be converted once the source files format is finalized
- Timeline is now its standalone app that reads the source files on startup
- Each entry now supports links (jump to entry) as a side-benefit of this feature
- Everything should look the same

2024-04-06 07:10 UTC, jchristgit commented
This is great !!!!!!

2024-05-04 06:15 UTC, jchristgit commented
This is still great !!!!!!!!!!!!!

2024-05-24 14:01 UTC, wookie184 requested changes
This is great, only one issue I noticed.

I wonder if we should make the date metadata optional (to allow for date ranges) and extract it from the file name by default. Currently there's some inconsistency with the month name (e.g. `Apr` vs `April`), which that would help avoid.

2024-05-24 14:01 UTC, wookie184 commented on pydis_site/apps/timeline/entries/2021-07-09_summer-code-jam-2021-cj8.md
> +based user interface (TUI), all designed around the theme of “think inside the
This adds an unwanted space.
Before:
![image](https://github.com/python-discord/site/assets/22353562/a8db93db-c5ab-4df8-a87b-bec186ed2822)
After:
![image](https://github.com/python-discord/site/assets/22353562/a2e02d91-ed2a-49cb-b103-0ffd209336e3)

2024-05-24 14:07 UTC, hedyhli commented
> I wonder if we should make the date metadata optional (to allow for date ranges) and extract it from the file name by default. This would help avoid the inconsistency of month names you mentioned

Good idea 👍

2024-06-20 15:23 UTC, jchristgit approved these changes
This is an excellent and super clean implementation - thank you very much!

2024-07-18 20:28 UTC, wookie184 approved these changes
We can leave making the date field optional and extracting from the file name to potentially another PR, this is great as-is so there's no point leaving it. Let's merge

2024-07-18 20:30 UTC, merged