Simple logging.
python-discord/site pull request #16
Opened 2018-02-17 23:44 UTC by 1mn

I don't know if this will show up in the docker logs like Inver wanted, so it might need testing in prod.

2018-02-17 23:47 UTC, gdude2002 requested changes
It might be worth using useful names for specific loggers in specific places, but for now I think this is mostly fine.

2018-02-17 23:47 UTC, gdude2002 commented on pysite/__init__.py
> +if log_level == 'debug':
Could do this via hasattr/getattr?

2018-02-18 00:13 UTC, gdude2002 submitted a review, later dismissed

2018-02-18 00:56 UTC, swedgwood reviewed
Looking good to me!

2018-02-18 00:56 UTC, shadycake commented on pysite/route_manager.py
> +            self.log.debug("")
Why is there an empty print here? (Now self.log.debug)

2018-02-18 00:59 UTC, swedgwood approved these changes
👍

2018-02-18 00:59 UTC, merged