Update resources.json
python-discord/site pull request #173
Opened 2019-01-15 09:52 UTC by kennethreitz

2019-01-15 11:40 UTC, lemonsaurus approved these changes
Oh hey, that looks like an excellent resource. Approved.

EDIT: oops, looks like a test is failing.

2019-01-15 11:42 UTC, lemonsaurus requested changes

2019-01-15 11:42 UTC, heavysaturn commented on static/resources.json
> +      }
needs a trailing comma here though.

2019-01-16 04:14 UTC, GhostofGoes approved these changes

2019-01-16 04:15 UTC, GhostofGoes commented
@heavysaturn I fixed the comma, can you re-approve?

2019-01-17 12:37 UTC, lemonsaurus approved these changes

2019-01-17 12:46 UTC, merged