#205: split models into multiple modules
python-discord/site pull request #207
Opened 2019-04-14 20:02 UTC by jchristgit

As discussed in #205, this merge request refactors models to use one model per file instead of a single huge monolith.

2019-04-14 20:32 UTC, lemonsaurus requested changes
looks good, but I think you left a duplicate file in there.

2019-04-14 20:32 UTC, lemonsaurus commented on pydis_site/apps/api/models/bot/infraction 3.py
> +from django.db import models
this file is a duplicate of `infraction.py`, right?

2019-04-15 12:33 UTC, lemonsaurus approved these changes

2019-04-15 17:19 UTC, jchristgit commented
Thanks!

2019-04-15 17:19 UTC, merged