[#192] Flake8-docstrings
python-discord/site pull request #215
Opened 2019-04-21 15:22 UTC by gdude2002

Adds flake8-docstrings along with the configuration discussed in #192 and on Discord. Fixes #192.

2019-04-21 21:29 UTC, gdude2002 commented
I've done as many docstrings as I could, but I'm a little stuck on them. Here's what's left:

```py
./pydis_site/apps/api/serializers.py:16:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:24:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:46:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:56:1: D102 Missing docstring in public method
./pydis_site/apps/api/serializers.py:68:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:76:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:85:1: D102 Missing docstring in public method
./pydis_site/apps/api/serializers.py:99:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:100:1: D102 Missing docstring in public method
./pydis_site/apps/api/serializers.py:114:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:125:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:132:1: D102 Missing docstring in public method
./pydis_site/apps/api/serializers.py:136:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:144:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:152:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:160:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:168:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:178:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:186:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:194:1: D101 Missing docstring in public class
./pydis_site/apps/api/serializers.py:205:1: D101 Missing docstring in public class
./pydis_site/apps/api/viewsets/bot/nomination.py:9:1: D101 Missing docstring in public class
```

Could someone give me a hand on understand what's going on with these classes, or help me to document them somehow?

2019-04-21 21:42 UTC, jchristgit commented
I'll push docstrings to this branch for the missing ones if you don't mind

2019-04-21 21:54 UTC, gdude2002 commented
Sure thing, go for it

2019-04-22 12:04 UTC, jchristgit requested changes
Rock solid, but I still see some inconsistencies between spacing after docstrings (in methods) and no spacing. I think we should consistently have a newline after docstrings in methods. what do you think?

2019-04-22 12:04 UTC, jchristgit commented on Pipfile
> +flake8-docstrings = "*"
This should be pinned, or tilded.
```suggestion
flake8-docstrings = "~=1.3.0"
```

2019-04-22 16:04 UTC, gdude2002 commented
I don't disagree, but it surprises me that we can't actually lint for that - what should we do about it?

2019-04-24 09:55 UTC, lemonsaurus requested changes
Excellent quality PR.

2019-04-24 09:55 UTC, lemonsaurus commented on pydis_site/apps/home/templatetags/extra_filters.py
> +    Kind of surprising that Django doesn't come with this one, actually...
I think we can probably live without this line.

2019-04-24 09:56 UTC, lemonsaurus commented
As for the "what do we do about that" question from earlier - Well, for now, we just make sure to consistently put a newline. Not much else we can do about it for now, maybe we could make a pull request to `flake8-docstrings`?

2019-04-24 09:59 UTC, gdude2002 commented
Addressed.

Yeah, maybe that's a good idea. It's actually `pydocstyle` under the hood - I have to wonder if they'd accept it though. Is it part of the PEP?

2019-04-24 10:40 UTC, lemonsaurus commented
PEP257 actually is a bit complicated on this subject. It specifies that one-liner docstrings should _not_ be followed by a blank line, but that class docstrings (even one-liners) should. It does not make any specific requirements of multi-line docstrings, nor are there any examples to draw from in the PEPs.

If we look at a modern bit of python code written by a core dev, we see that there are no newlines after multi-line docstrings either for example in https://github.com/python/cpython/blob/master/Lib/asyncio/coroutines.py#L104:L109, which was written by `vstinner`.

That said, some parts of the standard library have absolutely zero regard for PEP8. the `collections` module for instance prefers to use single quotes for docstrings, sometimes not even triple single quotes. Other parts of the standard library uses multi-block comment docstrings (wtf) and many forego docstrings entirely.

So what about Guido himself? Well, after digging through some recent commits that he's made on his `mypy` project, it appears Guido consistently puts a newline after module docstrings and class docstrings, but never after method docstrings (neither oneliners nor multiliners).

![image](https://user-images.githubusercontent.com/2098517/56653528-1ed25200-668e-11e9-9b81-07ba006da63f.png)


So I guess that's the de-facto correct way to do it.

2019-04-24 10:42 UTC, lemonsaurus approved these changes

2019-04-24 10:48 UTC, gdude2002 commented
That's pretty interesting, thanks for looking into that.

I just remembered that `pydocstyle` actually does allow you to specify one of a number of different code style presets, so they may actually accept that PR. Can't hurt to ask, right?

2019-04-24 11:20 UTC, lemonsaurus commented
Actually this looks perfectly enforcable now that I've had a look at it.

D202 | No blank lines allowed after function docstring
D204 | 1 blank line required after class docstring

These two are all that's preventing us from linting for Guido-style docstring newlines.

2019-04-24 11:29 UTC, lemonsaurus commented
I think I'd like to suggest that we don't ignore those two rules, considering my above posts. This would have several advantages:
- Complies with PEP257 and PEP8
- Immediately enforcable with the linter
- It's how Guido and other core devs do it, why should we be any worse?

2019-04-24 12:28 UTC, SebastiaanZ commented
I'm all for following the general guidelines, but we've discussed this before and some people were vocal against the no-newline thing, since they didn't like the look of that. I don't think that's a particularly strong argument for going against the general conventions and an easy linter setup, but maybe they have a better reason I don't have for that, so it's not me who should be defending that point.

As always, I'm pretty pliable when it comes to rules like this: As long as we're consistent and the style doesn't hurt readability, I can live with the decisions we make. Personally, I'd stick with the official style guides, unless we have good reasons to deviate from them.

2019-04-24 12:34 UTC, lemonsaurus commented
I looked through the previous tickets where we talked about which rules to ignore in `flake8-docstrings` and we seem to have skipped discussing this. I know that in the past some users have been outspoken about keeping the newline, but I feel like in this case there good reasons to consider changing our policy on this. The most important of which is to be able to _enforce_ that consistency.

2019-04-24 12:35 UTC, scragly commented
These types of style choices are highly opinionated so will not always get a 100% agreed conclusion among contributors since everyone has their own history, influences and styles. The most important thing is consistency, in my own opinion, and in the end there's no negative outcome from being able to enforce this particular style through linting, it only improves the simplicity of being able to provide a consistent style since linting can be done automatically. It's an improvement for possible first time contributors.

2019-04-24 12:47 UTC, gdude2002 commented
Personally I prefer the extra newline, but I don't particularly mind not having it and I think consistency is definitely important.

2019-04-24 13:19 UTC, MarkKoz commented
Style-wise, either way is fine with me. But from a practical stand point, I think we should avoid making stylistic choices in such vein (i.e. simple formatting rules) that we cannot lint for within reason. Thus I am in favour of not having a newline after every docstring. As for whether it should be abolished completely or only for functions: again, I am impartial to this.

2019-04-24 13:22 UTC, lemonsaurus commented
With these two rules unignored, classes would require a newline, functions wouldn't allow one, and module docstrings presumably could go either way. But we don't use module docstrings that often anyway, so I don't really see that as a huge problem.

2019-04-24 13:24 UTC, lemonsaurus commented
I'd like to hear from @jchristgit and @sco1 before we make a decision, but I think so far it seems like the consensus is "it doesn't matter, just go with whatever we can lint so we can enforce it". I also agree with this.

2019-04-24 18:14 UTC, jchristgit approved these changes

2019-04-24 18:14 UTC, merged