Updated resources.json
python-discord/site pull request #227
Opened 2019-06-10 22:27 UTC by naever32

Added a learning resource.

2019-06-11 02:06 UTC, sco1 requested changes
Thanks for the link! From what's visible for free this seems to be a very well put together site. We'll have some more folks check it out in depth before a decision to merge is made.

For future reference, please include a more descriptive title & description for the PR so reviewers have some idea what they're looking at. Same goes for commit messages, as explained in our [Contributors Guideline](https://github.com/python-discord/site/blob/master/CONTRIBUTING.md).

2019-06-11 02:06 UTC, sco1 commented on static/resources.json
> +        "payment": "optional",
While the free tier provides a glimpse into the service & its offerings, realistically this is a paid service if you want to end with an understanding of Python.

2019-06-11 02:19 UTC, sco1 commented
The site also appears to be running on Python 2, which means it does not support a whole lot of modern Python features. With [Python 2 EOL coming 2020-01-01](https://python3statement.org/), I can't recommend adding this to our resources until it's been updated.

![image](https://user-images.githubusercontent.com/5323929/59238876-9ff99000-8bcd-11e9-9de4-704ae4ca1384.png)

2019-06-11 18:49 UTC, naever32 commented
> For future reference, please include a more descriptive title & description for the PR so reviewers have some idea what they're looking at. Same goes for commit messages, as explained in our [Contributors Guideline](https://github.com/python-discord/site/blob/master/CONTRIBUTING.md).

I will keep this in mind for next time, sorry. Did not know it was py2.

2019-06-11 19:14 UTC, lemonsaurus commented
@naever32 that's alright. FYI we've been in touch with the creator and they say they're working on porting this over to Python 3. We will probably be open to adding this resource once that's been done, so we'll stay in touch with them and reopen this ticket once that happens. 

I'm gonna close it for now, though.

2019-06-11 19:14 UTC, closed without merging

2019-10-29 13:45 UTC, tehybel commented
Hi guys,
The site has been running Python 3 for a while now:
![version](https://user-images.githubusercontent.com/7711239/67772204-f3c02500-fa59-11e9-97dd-766b8aa306dd.png)
@sco1 are you willing to reconsider adding it to the learning resources list? 

(Just let me know if any of you need a free membership to test out all the lessons. I run the site.)

By the way, the site has a bunch of free challenges now (https://pythonprinciples.com/challenges/), so perhaps setting `"payment": "optional"` may make sense at this point, though that's up to you.

2019-10-29 15:08 UTC, sco1 commented
Hello, welcome back!

I’ll make a note for folks to check it out again and we’ll go from there!

2020-02-22 14:06 UTC, lemonsaurus commented
@tehybel I'm giving it a spin now, and running into a strange bug with some of the free content. Any idea why this perfectly valid 3.6 feature is being interpreted as a SyntaxError?

![image](https://user-images.githubusercontent.com/2098517/75093752-e852b580-5584-11ea-9b60-2f2b229ac8d9.png)

2020-02-22 14:15 UTC, lemonsaurus commented
@tehybel here's another interesting thing that should've worked in 3.7:

![image](https://user-images.githubusercontent.com/2098517/75093879-32886680-5586-11ea-9f7c-bf3f4f194d0c.png)

2020-02-22 14:18 UTC, lemonsaurus commented
This feature is 3.5 
![image](https://user-images.githubusercontent.com/2098517/75093915-872be180-5586-11ea-84ba-e7314c6adeaa.png)

2020-02-22 14:21 UTC, lemonsaurus commented
meanwhile, this feature works and it's 3.7 only: 
![image](https://user-images.githubusercontent.com/2098517/75093961-ed186900-5586-11ea-91ad-2875d198c87a.png)

Looks like you're running some sort of pseudo-3.7

2020-02-22 14:23 UTC, lemonsaurus commented
It doesn't even support f-strings, which are sort of the keystone python 3 feature that everyone loves - 
![image](https://user-images.githubusercontent.com/2098517/75094000-3963a900-5587-11ea-9952-a8c89d502ff7.png)

2020-02-22 14:33 UTC, lemonsaurus commented
@tehybel 

Overall, I think this project shows promise and there are definitely good parts, but I don't think we can recommend this in our resources list until it supports (and teaches) modern Python 3 features, like f-strings, type annotations and asyncio.

Feel free to let us know if you add support for these things, and we'll be glad to reconsider it.

2020-02-22 16:46 UTC, tehybel commented
@lemonsaurus Thank you for taking the time to tell me about all this, it really is appreciated. There is definitely a bug causing most of these issues; I think the module that parses the syntax tree of user input to provide helpful feedback needs an update. I'll look into it.

I don't believe that type annotation and asyncio are in scope for this course, since it is for complete beginners. Expanding the course contents to cover more advanced concepts isn't a priority at this time.

Either way, thanks again for your time, and I'll look into the issues you described.

2020-02-22 17:17 UTC, lemonsaurus commented
@tehybel

I suppose asyncio might fall outside the scope of a beginners course, but I think a precursory glance at how type annotations look and work would fit well in a beginners course. it is, after all, syntax. it's not very difficult, and I don't think a beginners course should leave its takers confused about basic syntax when they encounter it.