Create offensive message model for python-discord/bot#617
python-discord/site pull request #300
Opened 2019-10-25 11:24 UTC by Akarys42

Hi, this PR add a new offensive message model needed for python-discord/bot#617. 

This PR closes #222.

2019-10-25 16:06 UTC, SebastiaanZ requested changes
I think it would also be a good idea to add the model to the admin back-end, so we can inspect it if needed.

2019-10-25 16:06 UTC, SebastiaanZ commented on pydis_site/apps/api/migrations/0046_offensivemessage.py
> +    ]
This will conflict with the already merged reminder jump_url migration.

2019-10-25 16:06 UTC, SebastiaanZ commented on pydis_site/apps/api/migrations/0046_offensivemessage.py
> +                ('delete_date', models.DateField(help_text='The date on which the message will be auto-deleted.', validators=[pydis_site.apps.api.models.bot.offensive_message.future_date_validator]))
Why did you choose to only save the date instead of a datetime precisely a week after the original message? We already have a `Scheduler` base class in the `bot` repo that can be used to create scheduled deletions, just like how it's used to remove infractions after a certain period. I think that's going to save an additional custom implementation of the removal-after-delay logic.

2019-10-25 16:06 UTC, SebastiaanZ commented on pydis_site/apps/api/viewsets/bot/offensive_message.py
> +
Does this route take any parameters or are we always returning all the entries in the database?

2019-10-25 16:06 UTC, SebastiaanZ commented on pydis_site/apps/api/viewsets/bot/offensive_message.py
> +    Requires an API token.
Are you planning to use this endpoint to delete the entries after the corresponding messages have been successfully removed from the guild? I don't think I've seen it in use in the `bot` PR, but I've only taken a cursory view at that one. If we're not going to use it, I don't think we should expose a delete method.

2019-10-25 16:06 UTC, SebastiaanZ commented on pydis_site/apps/api/viewsets/bot/offensive_message.py
> +class OffensiveMessageViewSet(
I'd like to see tests for this model that guarantee the API we want for it. This means that if we ever change anything in the settings later, the tests will reveal if it had any undesirable side-effects on the endpoint.

2019-10-26 15:20 UTC, Akarys42 commented
Updated.

2019-11-05 09:01 UTC, SebastiaanZ requested changes

2019-11-05 09:01 UTC, SebastiaanZ commented on pydis_site/apps/api/tests/test_offensive_message.py
> +        self.assertEqual(response.status_code, 400)
There are several reasons for why the API could return a `400` response; I think would be a good idea to assert that you're getting the appropriate response here by also asserting the message the API returns. See this infraction test, for an example:

https://github.com/python-discord/site/blob/8cc1f03297598629b27fb0b1adab82160505e879/pydis_site/apps/api/tests/test_infractions.py#L215-L218

This also holds for the other test methods, but I think you get the idea.

2019-11-05 09:01 UTC, SebastiaanZ commented on pydis_site/apps/api/migrations/0047_merge_20191025_1920.py
> +    ]
I don't think it's necessary to include a merge migration, since the diverging migration paths are not actually a part of master yet. To keep a clean history, I would just make sure that your migration nicely follows the current migrations we have. (In other words, this is only necessary for your local set-up since other branches have been merged in the mean time; I think it's better to clean up the local migration history instead of making it more complex.)

2019-11-05 09:01 UTC, SebastiaanZ commented on pydis_site/apps/api/migrations/0048_auto_20191025_1921.py
> +    ]
This is another migration that's necessary for you locally, since you're migrating from one local database state to another by altering the `delete_date` field from a `DateField` to a `DateTimeField`, but is not that relevant for public history. Your pull request basically introduces a single, atomic change in the database: a new model; ideally, this is just captured in a single migration that handles that.

2019-11-05 09:01 UTC, SebastiaanZ commented on pydis_site/apps/api/viewsets/bot/offensive_message.py
> +    CreateModelMixin, ListModelMixin, DestroyModelMixin, UpdateModelMixin, GenericViewSet
Is there ever a case where we use PUT or PATCH methods to update the entries in the table? I don't see it mentioned in the docstring and there are no tests for those methods in `test_offensive_message`, but you did include the [`UpdateModelMixin`](https://www.django-rest-framework.org/api-guide/generic-views/#updatemodelmixin) here, which will implement these (partial/full) update methods for existing entries.

This is related to the next comment as well, but I don't really see a use-case for updating existing entries; we mainly want to be able to add them, list them, and delete them when we're done with them.

Using these mixins:
```suggestion
    CreateModelMixin, ListModelMixin, DestroyModelMixin, GenericViewSet
```
will make sure we're able to create, list, and destroy entries, but nothing else.

All these actions should be confirmed by tests and, preferably, we should test that using a method that's not allowed (PUT/PATCH) results in a `405` response.

2019-11-05 09:01 UTC, SebastiaanZ commented on pydis_site/apps/api/viewsets/bot/offensive_message.py
> +    View providing CRUD access to reminders.
Probably a mistake from copy-pasting, but "reminders" does not fit here. I also don't think we should provide an `update` interface, because I don't really see a use-case for it. We either add, list, or delete the offensive messages here; the message id, channel id, and deletion date should probably not change.

2019-11-05 09:01 UTC, SebastiaanZ commented on pydis_site/apps/api/viewsets/bot/offensive_message.py
> +    - 404: if a offensive message object with the given `id` does not exist
I don't see tests for this API interface, but it's an important API method to have.

2019-11-16 17:54 UTC, SebastiaanZ approved these changes

2019-12-03 22:26 UTC, MarkKoz requested changes

2019-12-03 22:26 UTC, MarkKoz commented on pydis_site/apps/api/urls.py
> +    'offensive-message',
I think this should be plural to be consistent with other routes. Docs would need to be updated with the correct route too.

2019-12-15 05:02 UTC, MarkKoz approved these changes

2019-12-15 05:11 UTC, merged