Mobile optimisation
python-discord/site pull request #33
Opened 2018-03-01 17:56 UTC by JoeBanks13

New optimisations on mobile:
- Terminal removed in favor of error message 
![image](https://user-images.githubusercontent.com/20439493/36860644-d16b5da8-1d79-11e8-8c87-967ca0753332.png)
- New dropdown on small screens
![image](https://user-images.githubusercontent.com/20439493/36860663-da20256e-1d79-11e8-99b9-51ac4a228d00.png)
- Button fixed on mobile displays
![image](https://user-images.githubusercontent.com/20439493/36860690-e7fb853e-1d79-11e8-8e53-2b39be29f90c.png)

2018-03-02 09:37 UTC, gdude2002 requested changes
Does this still look the same on desktop?

2018-03-02 09:37 UTC, gdude2002 commented on static/css/window.css
>  }
Missing newline at end of file

2018-03-02 09:37 UTC, gdude2002 commented on templates/errors/error.html
> +           <p style="color: #e84149; font-family: monospace;" class="error-header uk-text-large uk-text-break">{{ error_title }}</p>
Is there no UIKit class for this?

2018-03-02 18:43 UTC, lemonsaurus submitted a review, later dismissed
Apart from what gdude already mentioned, this looks production ready to me.

2018-03-03 10:58 UTC, gdude2002 commented on templates/errors/error.html
> +           <p style="color: #e84149; font-family: monospace;" class="error-header uk-text-large uk-text-break">{{ error_title }}</p>
There is no UIKit class for this

2018-03-03 10:59 UTC, gdude2002 approved these changes

2018-03-03 11:33 UTC, lemonsaurus approved these changes
excellent changes.

2018-03-03 22:14 UTC, merged