API for tags
python-discord/site pull request #34
Opened 2018-03-03 21:05 UTC by 1mn

2018-03-03 22:18 UTC, gdude2002 commented on pysite/base_route.py
> +        elif error_code is ErrorCodes.database_error:
I'm not gonna fail your PR for this block because we need to rethink this entire system - but this is inconsistent.

2018-03-03 22:19 UTC, gdude2002 commented on pysite/route_manager.py
> +        self.app.config["SERVER_NAME"] = os.environ.get("SERVER_NAME", "pythondiscord.local:8080")
You guys really hate actually setting your env vars, don't you? :P

2018-03-03 22:27 UTC, gdude2002 requested changes

2018-03-03 22:27 UTC, gdude2002 commented on pysite/views/api/bot/tags.py
> +class TagsView(APIView, DBMixin):
Should the methods in this class be validated? We have a decorator for that.

2018-03-03 23:47 UTC, AnonGuy commented on pysite/database.py
> +               durability: str="hard", return_changes: Union[bool, str] = False
Change `str="hard"` to `str = "hard"` to remain consistent with PEP8

2018-03-04 14:22 UTC, lemonsaurus commented on pysite/base_route.py
> +        elif error_code is ErrorCodes.database_error:
I think we should remove all that stuff, after the discussion we already had. But it's not really something we should do on this PR maybe. I can remove the additions I made into the system, though.

2018-03-05 22:43 UTC, gdude2002 approved these changes

2018-03-06 09:33 UTC, jerbob approved these changes

2018-03-06 19:03 UTC, jerbob approved these changes

2018-03-06 19:05 UTC, merged