Removes django-crispy-bulma as a dependency.
python-discord/site pull request #368
Opened 2020-07-14 21:06 UTC by lemonsaurus

django-crispy-bulma is not being maintained, and looks like it has a bleak future. I'm considering just archiving it, to be honest. 

As such, it has no place in our site. This PR removes it as a dependency, which should help unblock #346.

2020-07-14 21:20 UTC, MarkKoz requested changes
Got an error when logging in as admin and then trying to delete the account

![bild](https://user-images.githubusercontent.com/1515135/87477527-1b9deb80-c5dd-11ea-80bf-8abf7f851728.png)

2020-07-14 22:08 UTC, lemonsaurus commented
Yeah, I can see why that was happening @MarkKoz. The `django-crispy-forms` dependency was configured in settings.py to use bulma as its template folder, which doesn't exist without `django-crispy-bulma`. 

Turns out `django-crispy-forms` was only being used on that one page, so I refactored it to just use pure Django forms and no layout magic.

2020-07-14 22:15 UTC, MarkKoz approved these changes

2020-07-15 02:35 UTC, kosayoda approved these changes

2020-07-15 02:36 UTC, merged