Add a brief footer with a link to the repo
python-discord/site pull request #37
Opened 2018-03-05 04:32 UTC by schwartzadev

Of course, we can add to this and include whatever y'all like -- let me know if you would like to include any specifics and I'd love to add them!

2018-03-05 22:24 UTC, gdude2002 commented on templates/main/base.html
> +    <p>Developed collaboratively on <a href="https://github.com/discord-python/site">Github</a> • 2018</p>
It's generally good practise to use HTML entities with unusual characters. Helps avoid possible encoding issues.

2018-03-05 22:28 UTC, 1mn commented
Does the UIKit add any special visual elements to the page based on this code? If so, can we see a picture in the PR of how it looks?

2018-03-06 19:38 UTC, 1mn commented
@schwartzadev did you see this comment?

2018-03-07 05:03 UTC, schwartzadev commented
@1mn yes - I'm having trouble with my environment as of now -- maybe someone else could pull and take a screenshot?

2018-03-10 10:35 UTC, gdude2002 commented
Here's how it looks. Needs styling for sure.

![image](https://user-images.githubusercontent.com/204153/37241280-b205afaa-244e-11e8-964f-10a8be3d2c5a.png)

2018-03-11 19:49 UTC, schwartzadev commented
Here's how it looks now
![sample](https://i.imgur.com/emhIEkh.png)

2018-03-11 20:00 UTC, 1mn commented
That's not too shabby, actually.

2018-03-11 21:59 UTC, 1mn commented on templates/main/base.html
> +        <p>Developed collaboratively on <a href="https://github.com/discord-python/site">Github</a> • 2018</p>
The • symbol should not be a literal, but instead should use the equivalent html entity.

2018-03-11 22:00 UTC, lemonsaurus requested changes
local_vars.env is not relevant to this PR.

2018-03-17 01:40 UTC, lemonsaurus approved these changes

2018-03-17 01:41 UTC, 1mn commented
This seems okay to me. We can merge if someone else approves of it as well. @gdude2002, can you look over it?

2018-03-17 13:00 UTC, gdude2002 approved these changes
Looking good! I would have liked it to stick to the bottom of the screen when the page is too short to fill it, but honestly that isn't a massive big deal, and it's *super complicated* (I just gave it a try myself).

Good work!

2018-03-17 13:00 UTC, merged