Add mentions field to Reminders model
python-discord/site pull request #370
Opened 2020-07-16 07:27 UTC by kosayoda

To facilitate [bot/#1026](https://github.com/python-discord/bot/issues/1026), this PR adds a field to store the IDs of Member and Role objects.

No validation is done other than ensuring the ID is greater than 0, since we just ignore the ID if it doesn't convert to a valid Member/Role object on the bot side.

2020-07-19 01:58 UTC, MarkKoz requested changes
Is there any compelling reason we'd still need to track the author? Can we just lump their ID in with the rest of the mentions?

2020-07-19 01:58 UTC, MarkKoz commented on pydis_site/apps/api/tests/test_reminders.py
> +        )
It isn't necessary to create these objects since there's FK being used. Just use some integer literals for the IDs in the test.

2020-07-19 01:58 UTC, MarkKoz commented on pydis_site/apps/api/viewsets/bot/reminder.py
> +    ...     'jump_url': Optional[str]
I believe `jump_url` isn't optional according to the model.

2020-07-19 04:42 UTC, kosayoda commented
> Is there any compelling reason we'd still need to track the author? Can we just lump their ID in with the rest of the mentions?

Currently, the `author` field is a FK to a `User`. Getting all the reminders set by a particular `User` is trivial, and although we could filter by an index to the array, I don't think it's ideal.

More importantly, since I'm using an `ArrayField` to store the list of IDs, there's also no way to cascade delete reminders when the author leaves the server (assuming we go through with storing the author ID in the `mentions` field).

I'll address your other changes.

2020-07-19 04:43 UTC, MarkKoz commented
Ah right we need to know the author cause we have a list reminders command.

2020-07-19 05:13 UTC, MarkKoz approved these changes

2020-07-20 17:55 UTC, Den4200 approved these changes
It looks good to me.

2020-07-20 17:56 UTC, merged