Add a validator for documentation package names.
python-discord/site pull request #373
Opened 2020-08-03 20:25 UTC by Numerlor

https://github.com/python-discord/bot/pull/1014 will introduce a restriction on the package names to `a-z` and `_` because they will be used directly for stats. This PR implements that restriction on the site side.

2020-08-26 23:18 UTC, lemonsaurus approved these changes
This looks good to me.

2020-09-28 16:47 UTC, ks129 approved these changes

2020-10-08 00:21 UTC, MarkKoz requested changes
You should document in the viewset that a 400 will be returned by the POST due to the regex validator failing.

2021-03-14 23:43 UTC, Numerlor commented
> You should document in the viewset that a 400 will be returned by the POST due to the regex validator failing.

Isn't the current documentation pointing the user to see the response on 400s enough?
https://github.com/python-discord/site/blob/de7c6b37623464579794dcfb00db0ff106c7dc82/pydis_site/apps/api/viewsets/bot/documentation_link.py#L48-L60

2021-03-15 19:09 UTC, MarkKoz approved these changes

2021-04-19 07:02 UTC, merged