Add deployment info and set up Sentry releases
python-discord/site pull request #376
Opened 2020-08-21 23:44 UTC by lemonsaurus

Fixes #372 
Fixes #377

This adds two small changes related to git SHA.

## Add deployment info to all views
![image](https://user-images.githubusercontent.com/2098517/90943123-c5f90200-e418-11ea-919e-a3804783ae1b.png)

This is a useful bit of information that we can use to validate our assumptions about whether a deployment was successful.

## Set up Sentry Releases
This will allow us to pinpoint exactly which commit has introduced a new bug in Sentry, and should provide valuable context to errors we experience.

![image](https://user-images.githubusercontent.com/2098517/90944287-1b83dd80-e41e-11ea-8019-bbf5397a8c0f.png)

2020-08-22 01:39 UTC, MarkKoz requested changes

2020-08-22 01:39 UTC, MarkKoz commented on pydis_site/utils/utils.py
> +    return GIT_SHA
This seems redundant. Is this for coverage or something?

2020-08-22 01:39 UTC, MarkKoz commented on pydis_site/templates/wiki/base.html
> +  <!-- Git hash for this release: {{ git_sha }} -->
Is this redundant? It causes the comment to show up twice for wiki pages

```html
<body class="site">
  <!-- Git hash for this release: 52d7ae050d32df7ceda6888f8a60590ceb0e37dc -->

<main class="site-content">
  

  
  <!-- Git hash for this release: 52d7ae050d32df7ceda6888f8a60590ceb0e37dc -->
  
    


<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
```

2020-08-22 01:44 UTC, lemonsaurus commented on pydis_site/utils/utils.py
> +    return GIT_SHA
Yep.

2020-08-22 01:46 UTC, lemonsaurus commented on pydis_site/templates/wiki/base.html
> +  <!-- Git hash for this release: {{ git_sha }} -->
oh. my mistake, I was sure the wiki base didn't extend the other base. Removing it.

2020-08-22 01:47 UTC, MarkKoz commented on pydis_site/utils/utils.py
> +    return GIT_SHA
Ignoring the line with `# pragma: no cover` seems better than writing a function to get it to stop complaining. I don't know how to write a proper test for this anyway (like testing that the templates use it or something).

2020-08-22 01:48 UTC, lemonsaurus commented on pydis_site/utils/utils.py
> +    return GIT_SHA
sorry, I misread this part. you're saying why not just import the constant

Well, we could do that, I guess I mostly made this because it feels misleading to call it a util if it's not even a function, but that's not much of a justification.

2020-08-22 01:49 UTC, MarkKoz commented on pydis_site/utils/utils.py
> +    return GIT_SHA
How about calling it `constants.py` then?

2020-08-22 01:50 UTC, lemonsaurus commented on pydis_site/utils/utils.py
> +    return GIT_SHA
originally this function had all three lines of code, but then I realized it would be super wasteful to check the SHA every time this was called, so I moved it up to the top of the file. And now we're just left with, well, this.

2020-08-22 01:57 UTC, MarkKoz approved these changes

2020-08-22 01:57 UTC, MarkKoz commented on pydis_site/constants.py
> +repo = git.Repo(search_parent_directories=True)
Maybe this should be "private" but I'm not too fussed at this point.

2020-09-02 21:19 UTC, jb3 approved these changes

2020-09-02 21:19 UTC, merged