Dewikification - Create events app
python-discord/site pull request #417
Opened 2020-10-26 17:59 UTC by ks129

- Created special base template that all other templates that is in events app must extend.
- Created events app that have 2 views: Static index view and dynamic page view. All event pages is located under events app directory in `pages` folder.
- When requested page is directory, then this look for `_index.html` inside this directory.
- Covered views with tests
- Migrated Summer Code Jam 2020 base page and rules page to this system.
- Also migrated Jams part of static events index page.
- General Jams page created with content "ToDo!"
- Created sidebar for Summer Code Jam 2020
- Created CSS for base template of events.
- Closes #385 

**Images:**
![Screenshot 2020-10-26 at 19 55 30](https://user-images.githubusercontent.com/45097959/97209681-4fd09d00-17c5-11eb-8550-e59c18c83ac3.png)
![Screenshot 2020-10-26 at 19 55 44](https://user-images.githubusercontent.com/45097959/97209689-5232f700-17c5-11eb-8f7a-685570975968.png)
![Screenshot 2020-10-26 at 19 55 53](https://user-images.githubusercontent.com/45097959/97209698-53fcba80-17c5-11eb-88b4-162dc2f81ebf.png)
![Screenshot 2020-10-26 at 19 56 06](https://user-images.githubusercontent.com/45097959/97209706-55c67e00-17c5-11eb-9d3b-69b00c0e3ef3.png)

I hope this get merged faster than content app PR #393, as this doesn't contain so much *logic* and should be easier to review.

2020-10-28 17:44 UTC, jerbob commented on pydis_site/apps/events/urls.py
> +    path("", IndexView.as_view(), name="events"),
```suggestion
    path("", IndexView.as_view(), name="index"),
```
I touched on this one in the other PR, but using `{% url 'events:index' %}` is more explicit than `{% url 'events:events'%}`.

2020-10-28 17:52 UTC, jerbob requested changes

2020-10-28 17:52 UTC, jerbob commented on pydis_site/apps/events/urls.py
> +    re_path("(?P<path>.+)/$", PageView.as_view(), name="page"),
```suggestion
    path("<str:path>/", PageView.as_view(), name="page"),
```
You don't need to use `re_path` here, you can use `path`'s [builtin captured values.](https://docs.djangoproject.com/en/3.1/topics/http/urls/#example)

2020-10-28 17:53 UTC, jerbob commented on pydis_site/apps/events/urls.py
> +    path("", IndexView.as_view(), name="events"),
If you're actioning this, replace [these lines](https://github.com/python-discord/site/pull/417/files#diff-2fc0bf29e735c0301788f0619f6b28d3c2d43074a1f6cfe2a9a273eb64de2267R6-R7) in the index template with the url tag equivalents, e.g. `{% url 'events:index' %}`

2020-10-28 17:56 UTC, jerbob commented on pydis_site/apps/events/views/page.py
> +            path = path[:-1]
You can get rid of this if you're using `path`'s captured values, mentioned above.

2020-10-28 17:58 UTC, jerbob commented on pydis_site/apps/events/views/page.py
> +        page_path = PAGES_PATH.joinpath(path)
You can use `pathlib.Path`'s `__div__` overrides here, it's generally a bit cleaner than using `joinpath`.
```suggestion
        page_path = PAGES_PATH / path
```

2020-10-28 18:04 UTC, jerbob commented on pydis_site/apps/events/views/page.py
> +        return HttpResponse(template.render(Context()))
You could get rid of this boilerplate by using a `TemplateView` and defining `get_template_names` on it:
https://docs.djangoproject.com/en/3.1/ref/class-based-views/mixins-simple/#django.views.generic.base.TemplateResponseMixin.get_template_names

2020-11-08 16:51 UTC, jerbob commented on pydis_site/apps/events/views/page.py
> +        return [f"events/{settings.PAGES_PATH.name}/{self.kwargs['path']}"]
We're referencing `self.kwargs['path']` quite a lot throughout this method - I think it would be worth just assigning it `path: str = self.kwargs["path"]` at the start of this method, and referencing that instead.

2020-11-08 16:51 UTC, jerbob commented on pydis_site/templates/events/index.html
> +        <p>If you want to read more about Code Jams, visit our <a href="/events/code-jams">Code Jam info page</a> or watch this video showcasing the best projects created during the <strong>Winter Co
Missing url tag:
```suggestion
        <p>If you want to read more about Code Jams, visit our <a href="{% url "events:page" path="code-jams" %}">Code Jam info page</a> or watch this video showcasing the best projects created during the <strong>Winter Code Jam 2020: Ancient Technology</strong>:</p>
```

2020-11-08 16:59 UTC, ks129 commented on pydis_site/apps/events/views/page.py
> +        return [f"events/{settings.PAGES_PATH.name}/{self.kwargs['path']}"]
Do I have to use type hint?

2020-11-08 17:05 UTC, ks129 commented on pydis_site/apps/events/views/page.py
> +        return [f"events/{settings.PAGES_PATH.name}/{self.kwargs['path']}"]
Fixed.

2020-11-12 01:13 UTC, jerbob requested changes

2020-11-12 01:13 UTC, jerbob commented on pydis_site/apps/events/views/page.py
> +        return [f"events/{settings.PAGES_PATH.name}/path}"]
Looks like a typo here?
```suggestion
        return [f"events/{settings.PAGES_PATH.name}/{path}"]
```

2020-11-12 01:13 UTC, jerbob commented on pydis_site/templates/events/pages/code-jams/7/_index.html
> +            <li><a class="has-text-link" href="/events/code-jams/7/rules">Rules</a></li>
Beep boop URL tag
```suggestion
            <li><a class="has-text-link" href="{% url "events:page" path="code-jams/7/rules" %}">Rules</a></li>
```

2020-11-12 01:13 UTC, jerbob commented on pydis_site/templates/events/pages/code-jams/7/rules.html
> +            <li><a class="has-text-link" href="/events/code-jams/7">Summer Code Jam 2020</a></li>
```suggestion
            <li><a class="has-text-link" href="{% url "events:page" path="code-jams/7" %}">Summer Code Jam 2020</a></li>
```

2020-11-12 09:22 UTC, jerbob approved these changes

2020-11-15 20:00 UTC, jerbob approved these changes

2020-11-22 19:54 UTC, merged