Add activity blocks to Metricity
python-discord/site pull request #418
Opened 2020-10-27 01:55 UTC by jb3

Voice gate has been a success (in general)!

One downside we have observed is users spamming in order to meet the 50 messages threshold, this is dissatisfactory and will not be tolerated!

This PR introduces a new response in the metricity data endpoint to show how many 10 minute intervals the requested user has been active in. This means how many blocks of 10 minutes has the user sent at least one message in.

A threshold for this has not been decided on for this yet, but this will allow us to mandate that the user gets their messages over a period of time.

If we wanted we could use this instead of a message constraint and say that the user must sent at least one (or any number of) messages per 10 minutes for 6 ten minute blocks.

2020-10-27 03:49 UTC, MarkKoz requested changes
I think this file needs to be updated for the sake of local testing, right? https://github.com/python-discord/site/blob/master/postgres/init.sql

2020-10-27 09:03 UTC, thomaspet commented
Don't know enough about this to give anything more than a code-review

2020-10-30 16:06 UTC, MarkKoz approved these changes
I'm only doing a code review but it looks correct. I'm basing that on the assumption that all the other metricity code in master works since the code you added is following the established patterns.

2020-10-30 23:48 UTC, lemonsaurus approved these changes
I think the implementation looks fine here, but you should document the intent a little better.

2020-10-30 23:48 UTC, lemonsaurus commented on pydis_site/apps/api/models/bot/metricity.py
> +        """Query number of 10 minute blocks the user has been active during."""
Don't end a sentence with a preposition - especially not the preposition "during", that's just weird, dude.

2020-10-30 23:48 UTC, lemonsaurus commented on pydis_site/apps/api/models/bot/metricity.py
> +        """Query number of 10 minute blocks the user has been active during."""
Also, maybe you can describe some of the context for this? We should document some context _somewhere_, and I think this is the best option we have.

2020-10-30 23:49 UTC, l33tlinuxh4x0r approved these changes
Looks good to me.

2020-10-31 00:01 UTC, merged