Update year to 2020 in LICENSE
python-discord/site pull request #420
Opened 2020-10-30 10:09 UTC by hedythedev

Happy belated new year :tada:

2018 -> 2020

I don't think much description is needed 

If this is merged I will also update the licenses in the other repos (unless someone does it before me)

2020-10-30 10:15 UTC, Akarys42 requested changes
This is fine by me, but it is better if we make it inclusive (`2018-2020` instead of just `2020`).

Once this is done, we can merge it, but for the other repo one of the core devs will directly push to master, it will be easier this way. Thank you!

2020-10-30 10:15 UTC, Akarys42 commented on LICENSE
> +Copyright (c) 2020 Python Discord
Let's make it inclusive 
```suggestion
Copyright (c) 2018-2020 Python Discord
```

2020-10-30 10:22 UTC, hedythedev commented
It might be neater to squash the commits but I'm not on my computer at the moment

2020-10-30 10:26 UTC, Akarys42 approved these changes

2020-10-31 00:05 UTC, l33tlinuxh4x0r approved these changes
lol we missed 2019 and it is almost time for 2021 but looks good.

2020-10-31 00:57 UTC, jb3 approved these changes

2020-10-31 00:58 UTC, merged