Sentry SDK version bump, Git SHA simplification
python-discord/site pull request #439
Opened 2020-12-20 13:52 UTC by ks129

- Bumped Sentry SDK from 0.14 to 0.19.
- Inject Git SHA to container using build arguments.
- Use Git SHA from environment instead from GitPython package.
- Removed GitPython package.
- Added `.git` directory back to `.dockerignore`.

2020-12-20 17:08 UTC, MarkKoz approved these changes

2020-12-21 04:53 UTC, Den4200 approved these changes

2020-12-21 14:45 UTC, jb3 requested changes
Let's take this as an opportunity to change from the `pydis-site` prefix to `site`

2020-12-21 14:55 UTC, jb3 approved these changes

2020-12-21 14:55 UTC, merged