Oauth
python-discord/site pull request #45
Opened 2018-03-25 18:49 UTC by Zwork101

Let's finally get this out of the way!

2018-03-25 18:57 UTC, gdude2002 commented on pysite/database.py
> +               return_changes: Union[bool, str] = False) -> dict:
rude. :P

2018-03-25 19:11 UTC, Zwork101 commented on pysite/database.py
> +               return_changes: Union[bool, str] = False) -> dict:
Apeture suggested it last PR :p

2018-03-26 10:11 UTC, gdude2002 submitted a review, later dismissed
Not bad. A few comments there for you, and also:

* We should write a middleware to inject logged-in user info into the request object
* Your PR doesn't lint, and it seems that test coverage has been lowered

2018-03-26 10:11 UTC, gdude2002 commented on pysite/oauth.py
> +class OauthBackend(BaseBackend, DBMixin):
DBMixin was never designed for this. It's a mixin for route views, not just any object.

I suggest the following:
* Remove `_MAIN_BACK` from the module. Globals are bad.
* Store the database manager from the route manager on the object, via `self`.
* Move your outer functions into the class.
* Make sure the OauthBackend is accessible to the route manager - it needs to be stored within it.
* Finally, make the OauthBackend available to routes, if any of your routes need it.

2018-03-26 10:11 UTC, gdude2002 commented on pysite/views/main/oauth_resp.py
> +            'client_secret': "{client_secret}",  # Fill this in
`# fill this in`

2018-03-26 10:11 UTC, gdude2002 commented on pysite/views/tests/index.py
> +
:eyes:

2018-03-27 08:15 UTC, gdude2002 requested changes

2018-03-27 08:15 UTC, gdude2002 commented on app_test.py
> +class BaseEndpoints(SiteTest):
Empty testcase?

2018-03-27 08:15 UTC, gdude2002 commented on pysite/mixins.py
> +    def setup(cls: "DBMixin", manager: "pysite.route_manager.RouteManager", blueprint: Blueprint):
Wrong `cls` type hint

2018-03-27 08:15 UTC, gdude2002 commented on pysite/mixins.py
> +        cls._oauth = ref(manager.oauth_backend)
I still think we might want to be able to access this class directly, so a property like the following might be nice:

```py
@property
def oauth(self):
    return self._oauth()
```

2018-03-27 08:15 UTC, gdude2002 commented on pysite/oauth.py
> +        self.join_discord(token["access_token"], user["id"])
Is there any way we can detect that we needed to do this and let the user know on the site?

2018-03-27 08:15 UTC, gdude2002 commented on pysite/oauth.py
> +        self.db.insert("oauth_data", {"id": sess_id,
I don't think you're creating this table now.

2018-03-27 08:15 UTC, gdude2002 commented on pysite/oauth.py
> +        id = session.get("session_id")
Shadowing a builtin

2018-03-27 08:15 UTC, gdude2002 commented on pysite/views/main/index.py
> +class IndexView(OauthMixin, RouteView):
No, mixins come after base classes

2018-03-27 08:15 UTC, gdude2002 commented on pysite/views/main/index.py
> +        return self.render("main/index.html", logged_in=self.logged_in, login_url=DISCORD_OAUTH_REDIRECT)
`logged_in` is required on all pages. This parameter should be added in the `render()` method of the base class instead. I've already got one somewhere.

2018-03-27 08:15 UTC, gdude2002 commented on pysite/views/main/index.py
> +        return self.render("main/index.html", logged_in=self.logged_in, login_url=DISCORD_OAUTH_REDIRECT)
Also, we should have a login url ourselves that redirects to the Discord OAuth page.

2018-03-27 21:09 UTC, gdude2002 requested changes
I don't see anything about cookies here. Did you decide to remove the automatic server join after all?

2018-03-27 21:09 UTC, gdude2002 commented on pysite/base_route.py
> +
Now that the test is fixed, is it necessary to have moved this?

2018-03-27 21:09 UTC, gdude2002 commented on pysite/mixins.py
> +class OauthMixin:
This class needs documenting

2018-03-27 21:09 UTC, gdude2002 commented on pysite/route_manager.py
> +        # self.app.config["SERVER_NAME"] = os.environ.get("SERVER_NAME", "pythondiscord.local:8080")
Why?

2018-03-28 21:50 UTC, gdude2002 requested changes

2018-03-28 21:50 UTC, gdude2002 commented on pysite/base_route.py
> +
Bump

2018-03-28 21:50 UTC, gdude2002 commented on pysite/mixins.py
> +class OauthMixin:
Bump

2018-03-28 22:24 UTC, gdude2002 submitted a review, later dismissed

2018-03-28 22:32 UTC, gdude2002 submitted a review, later dismissed

2018-03-29 08:46 UTC, jerbob requested changes

2018-03-29 08:46 UTC, AnonGuy commented on app_test.py
> +        """check oauth redirects """
These docstrings aren't consistent with the others: `""" Check oauth redirects """`

2018-03-29 08:46 UTC, AnonGuy commented on app_test.py
> +    """ Test cases for the oauth.py file"""
These docstrings aren't consistent with the previous, add a space at the end pls

2018-03-29 08:51 UTC, gdude2002 approved these changes

2018-03-29 08:52 UTC, jerbob approved these changes

2018-03-29 08:52 UTC, merged