New filter schema
python-discord/site pull request #482
Opened 2021-04-27 09:01 UTC by Akarys42

Implements the new filter related schema described in #479. The definition of each model can be found on this issue.

It adds a bunch of new routes under `/bot/filters` for each model, for example `/bot/filter/filter_lists` will provide GET, POST, PUT and DELETE for the `FilterList` model.

It also adds a migration (number 70) that will convert our current filters to the new schema and set some defaults that should mimic our current setup. Note that it will use a default value if the description isn't set, we will have to set one.

Most of this PR is just REST framework boilerplate, enjoy!

Closes #479

*note: this PR targets the `filter-rewrite` branch instead of `main`, it can be merged at any time.*

2021-04-28 19:24 UTC, mbaruh requested changes
Thank you, that was record speed.

I think it's a good start so that we have something to test with. Aside from the minor comments below, there are two things I think are important:
* An endpoint to recursively fetch all data in the schema, so that we don't have to join tables manually on the bot side, and just make one API request on startup.
* Very detailed docs, to the point of saying where exactly you need to go to remove a kind of setting.

2021-04-28 19:24 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +    DENY: 0
What is the motivation to make it integer choices, rather than text choices as the infraction types below?

2021-04-28 19:24 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +VALID_PINGS = ("everyone", "here", "moderators", "onduty", "admins")
Is it necessary to define these? we could just have a list of role ID's.

2021-04-28 19:24 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +        help_text="Whenever this list is an allowlist or denylist"
```suggestion
        help_text="Whether this list is an allowlist or a denylist"
```

2021-04-28 19:24 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +    filter_dm = models.BooleanField(help_text="Whenever DMs should be filtered.")
```suggestion
    filter_dm = models.BooleanField(help_text="Whether DMs should be filtered.")
```

2021-04-28 19:24 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +        help_text="Whenever this filter should delete messages triggering it."
```suggestion
        help_text="Whether this filter should delete messages triggering it."
```

2021-04-28 19:24 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +        help_text="Roles and users who can bypass this filter."
How do you tell whether an ID belongs to a role or to a user? should be limited to roles IMO.

2021-04-28 19:24 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +        help_text="Whenever ths filter is currently enabled."
```suggestion
        help_text="Whether this filter is currently enabled."
```

2021-04-28 19:24 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +        help_text="The default action to perform."
Not really clear what that means
```suggestion
        help_text="What action to perform on the triggering user."
```

2021-04-28 19:24 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +        help_text="Where does this filter apply."
```suggestion
        help_text="The channels and categories in which this filter applies."
```

2021-04-28 19:24 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +class FilterOverride(models.Model):
Can we call it SettingsOverride? since we're overriding the settings.

2021-04-28 19:24 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +    filter_range = models.ForeignKey("ChannelRange", models.CASCADE, null=True)
I think these names should also be the names in FilterSettings.

2021-05-01 22:25 UTC, MarkKoz requested changes
I'm only reviewing the schema for now.

A mistake you've made is conflating one-to-many relationships with one-to-one relationships. Recall that a foreign key describes the former, not the latter. However, the relationships between settings and filters is one-to-one, as well as the relationship between settings and actions/ranges.

One-to-one relationships are kind of strange to me in the world of database design, since they _can_ be merged into a single table. There are some technical reasons for separating them (performance, different security policies, etc.), but I think the primary reason it's done here is for semantics. The argument is that it betters the understanding of the schema, and aides in the organisation and maintenance of it. 

The distinction between some of the models in the one-to-one-relationships seem a bit weak. Furthermore, it's not consistent e.g. the infraction fields arguably represent an infraction, so they should be in a separate table for semantic purposes too.

However, at least for the filters to settings relationship, I feel the decision to split them can still hold up. There would be a stronger case if the override was the exact same schema as the defaults (in which case the tables could be merged too), but unfortunately that seems impossible due to one needing to have nullable fields.

The idiomatic way to implement one-to-one relationships in Django is through [inheritance](https://docs.djangoproject.com/en/3.2/topics/db/models/#model-inheritance). The question is whether each model should have its own table or if the fields of the abstract parents should be instead in the child tables.

The latter sounds better to me, since I believe it'd avoid cross-table joins. Since the schema is managed through Django, it will still give the illusion of being separate where it matters. I wonder if it's possible to let the child dictate whether the inherited fields should be nullable; this would avoid defining two separate settings classes.

Note that, if needed, serialisation can be customised to organise things in a different manner than the schema represents it.

2021-05-01 22:25 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +    filters = models.ManyToManyField("Filter", help_text="The content of this list.", default=[])
This should not be a many-to-many relationship. It doesn't make sense for a filter to belong to multiple lists. It should be a one-to-many relationship, which is simply defined with a foreign key. Django supports [following relationship backwards](https://docs.djangoproject.com/en/3.2/topics/db/queries/#following-relationships-backward), if needed.

2021-05-01 22:25 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +        return f"Filter {'allow' if self.list_type == 1 else 'deny'}list {self.name!r}"
Don't hard-code this. It's like a normal Python enum, so you can do `FilterListType(self.list_type)` to get the name from the value. If it had labels defined, then, of course, you could use `FilterListType(self.list_type).label`.

2021-05-01 22:25 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +    user_dm = models.CharField(
`dm_content` is a better name.

2021-05-01 22:25 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +    )
There should be some validation (*ideally at the database level*) for these. It would make the API more robust. It is likely a mistake if a duration or reason is set but a type isn't. Furthermore, some infraction types don't support permanent durations. In fact, I'm not sure if this is normalised given that there's (sort of?) a relationship between the type and duration.

2021-05-01 22:25 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +        max_length=1000,
How did you decide this number for the dm and the reason?

2021-05-01 22:25 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +    additional_field = models.BooleanField(null=True, help_text="Implementation specific field.")
This is really limited, both in count and in type. It's conceivable for filters to use a value other than a boolean for setting and to use more than one filter-specific setting.

2021-05-01 22:25 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +    )
"Override" is ambiguous. What is it overriding? Only the help text would be able to explain that. Please name this "settings".

2021-05-01 22:25 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +    default = models.BooleanField()
What does this mean?

2021-05-01 22:25 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +    allowed_categories = ArrayField(models.IntegerField())
Something to keep in mind:

Arrays may be an obvious example of a non-atomic type. However, 1NF is ambiguous when it comes to atomicity. Arrays _can_ be treated as atomic types, but I believe this means one must not intend to establish any relationships with the individual elements in the array. My further understanding is that as a consequence, one should not intend to perform queries like "which filters does channel x have?"

2021-05-01 22:25 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +        raise ValidationError(f"{value!r} isn't a valid ping type.")
I propose to split the columns into roles and users so that each can contain homogenous types. Allowing arbitrary IDs for roles offers more flexibility and gets rid of some of the unintuitiveness and complexity of mixing roles and users in a single column.

The alternative to 2 arrays would be a single array with two columns - one for the ID and another for the type.

2021-05-01 22:25 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +    allowed_categories = ArrayField(models.IntegerField())
There should be validation (again, ideally at the database level) that

1. Each pair of arrays is mutually exclusive.
2. A duplicate value is not inserted into an array.

Starting to make be doubt if arrays are a suitable data type given such constraints. The four arrays could instead be 2 tables that have 2 columns - one for the ID and another for whether its allowed/disallowed. A primary key on the ID would address both of the validation points above.

2021-05-01 22:26 UTC, MarkKoz commented
Should look into which indexes will be good to have, but those can be added at any time down the road if it's now still too early to see how the data will get queried by the client.

2021-05-02 08:40 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +    )
There isn't actually anything preventing a mute from being permanent at the database level, we simply chose to not expose such a command on the bot side, but it's still possible to edit a mute to become permanent.
Likewise, notes and warnings seem to be marked as permanent, at least on the bot side.

2021-05-02 08:44 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +        max_length=1000,
For infraction reasons I believe there are issues with pagination on the bot side when they're too long. I know we limited nomination reasons to 1000 characters, and recall we did something similar with infractions.

For DM's however I agree the limit is probably not 1000.

2021-05-02 08:51 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +    allowed_categories = ArrayField(models.IntegerField())
Is it acceptable to have a field to tell whether it's a channel or a category? I'd rather these weren't split into multiple tables, as then it complicates grouping them on the bot side.

2021-05-02 08:53 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +        raise ValidationError(f"{value!r} isn't a valid ping type.")
I prefer the latter.

2021-05-02 09:02 UTC, mbaruh commented
@MarkKoz the guiding principle in deciding where we should split settings, is that columns in the settings table represent entries that can act independently. Splitting the infraction fields and the user DM field will mean, as you mentioned in the bot issue, that we might try to DM a user who has been already banned.

Regarding the overrides, it is possible to handle null values on the bot side and just say it means we should skip this attribute, and then make sure we're not writing null values to the defaults. However I'm not sure if this is a good idea.

2021-05-02 13:08 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +        raise ValidationError(f"{value!r} isn't a valid ping type.")
Sorrry, I made a mistake. To be clear, I meant a single table with 2 columns, not a single array.

2021-05-02 13:13 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +    allowed_categories = ArrayField(models.IntegerField())
Yes, I don't see why it wouldn't be acceptable. I don't believe it's possible for IDs to overlap either, if that was a concern.

As for your other point, keep in mind DRF lets you serialise the data in any way you want. It is not limited to being a 1:1 representation of the DB schema. Granted, it's easier when they do align, so the added work and any performance impacts should be weighed in along with  the benefit I mentioned in the original comment.

2021-05-02 13:15 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +        max_length=1000,
Can this import the infraction model and use its reason limit here instead of having two separate constants that need to be maintained in tandem?

2021-05-02 13:18 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +        max_length=1000,
This seems like a good approach, yeah.

2021-05-02 13:18 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +    )
I should have said it the other way around. Some infractions aren't meant to expire, like notes and warnings. That's a semantic limitation, not a technical one. However, there is validation imposed that prevents it.

We could allow it here and defer the error to when it actually tries to apply an infraction, but that is a bad idea.

2021-05-02 13:29 UTC, MarkKoz commented
> @MarkKoz the guiding principle in deciding where we should split settings, is that columns in the settings table represent entries that can act independently. Splitting the infraction fields and the user DM field will mean, as you mentioned in the bot issue, that we might try to DM a user who has been already banned.

As I mentioned, the JSON schema doesn't have to match the DB schema. Making a split for the reason you mention feels like encoding implementation-specific semantics/detsils into the DB schema. Again, one to one relationships are strange to see and I'm not sure about best practices here, so I don't feel too strongly either way. I do think it's worth discussing and looking into.

> 
> Regarding the overrides, it is possible to handle null values on the bot side and just say it means we should skip this attribute, and then make sure we're not writing null values to the defaults. However I'm not sure if this is a good idea. 

It isn't. It should be enforced in the DB level. As mentioned, we should look into some metaprogramming trickery to let the subclass make the inherited attributes all nullable, assuming the abstract class is the agreed-upon approach.

2021-05-02 13:34 UTC, mbaruh commented
Putting everything under settings, and then grouping fields in the JSON schema is fine by me.

2021-05-03 07:48 UTC, Akarys42 commented on pydis_site/apps/api/models/bot/filters.py
> +VALID_PINGS = ("everyone", "here", "moderators", "onduty", "admins")
There is no role ID for `here` though, how do we want to handle this?

2021-05-03 07:49 UTC, Akarys42 commented on pydis_site/apps/api/models/bot/filters.py
> +    DENY: 0
It was just a matter of having a little bit more lightweight field, as this is roughly just a boolean field, there are only two states. I don’t mind changing it though.

2021-05-03 07:50 UTC, Akarys42 commented on pydis_site/apps/api/models/bot/filters.py
> +        help_text="Roles and users who can bypass this filter."
We usually do that by trying to resolve it as a role and then a user. We cannot run into conflicts this way.

2021-05-29 17:09 UTC, Akarys42 commented
I don't think I'll be able to finish this in time as I have a bunch of other stuff to do, sorry.

If you wish to continue this PR feel free to ping me (Akarys#2780) in Discord, and I can give you a very detailed runbook of what is left to do.

2021-07-23 11:09 UTC, kosayoda commented on pydis_site/apps/api/models/bot/filters.py
> +    allowed_categories = ArrayField(models.IntegerField())
Given the situation where a channel/category could be whitelisted for a filter and blacklisted for another, how would a primary key on the ID work to address the validation issues? From what I can see of the current implementation, a `ChannelRange` entry is just the domain in which a filter applies.

2021-07-24 16:25 UTC, MarkKoz commented on pydis_site/apps/api/models/bot/filters.py
> +    allowed_categories = ArrayField(models.IntegerField())
It's been a long time since I've looked into this. I think it'd have to be a composite PK on the channel ID and the filter ID.

2021-08-27 18:57 UTC, mbaruh commented on pydis_site/apps/api/models/bot/filters.py
> +    default = models.BooleanField()
I think "default" should be removed.

2022-05-08 14:57 UTC, closed without merging