Add books - #1x28c
python-discord/site pull request #51
Opened 2018-04-11 19:26 UTC by schwartzadev

2018-04-11 19:45 UTC, gdude2002 commented
The format used for the JSON file has changed.

Where you'd get a single `url` before, each resource now has a `urls` attribute that is a list. It looks like this:

```json
"urls": [
  {
    "title": "Website",
    "url": "https://codecombat.com/",
    "icon": "regular/link"
  },
  {
    "title": "GitHub",
    "url": "https://github.com/codecombat/codecombat",
    "icon": "branding/github"
  }
],
```

The icons are font-awesome icons, and you can use any icons from font-awesome 5 (free or pro). A full list of these icons can be found [here](https://fontawesome.com/icons).

Please note that icons are given in the form `style/name`. Valid styles include `branding`, `regular`, `light` or `solid`. Font-awesome icons are varied based on the style you pick, so check which one you need from the icon list above!

2018-04-13 09:14 UTC, gdude2002 requested changes
Overall a good set of changes. I would like to comment that the description key here is to describe the book itself - who it's for, what it covers, and so on. `"Clear, Concise and Effective Programming"` comes off as more of like a catchphrase. Show that you know what the book is about.

2018-04-13 09:14 UTC, gdude2002 commented on static/resources.json
> +        "urls": [
There is a physical version that can be bought at https://www.swaroopch.com/buybook/

2018-04-15 08:33 UTC, lemonsaurus requested changes
if you address mine and gdudes comments, I think we're ready to merge.

2018-04-15 08:33 UTC, 1mn commented on static/resources.json
> +      "Automate the Boring Stuff with Python": {
There's also a Udemy course for this. Can we add that too? 

Here's a link with a coupon added that is always going to cost 10 dollars.

https://www.udemy.com/automate/?couponCode=FOR_LIKE_10_BUCKS

2018-04-20 19:08 UTC, 1mn commented
@schwartzadev Just making sure you noticed that we requested some changes.

2018-04-26 11:49 UTC, gdude2002 commented
It's been 15 days since there was any activity on this PR. Are you going to address our changes, @schwartzadev?

2018-04-26 12:32 UTC, 1mn commented
if we don't see an answer to this today, I vote we close this PR and just finish this task ourselves. I've been missing this change for weeks. I will ping Andrew on discord as well.

2018-04-27 07:42 UTC, 1mn commented
Still no word from Andrew on this.

2018-04-27 09:38 UTC, 1mn commented
Closing PR.

2018-04-27 09:38 UTC, closed without merging

2018-04-27 23:27 UTC, schwartzadev commented
Sorry y'all - I've been busy and won't be able to work on this for a while.
Good luck and my apologies.

On Fri, Apr 27, 2018 at 3:38 AM, Leon Sandøy <notifications@github.com>
wrote:

> Closing PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/discord-python/site/pull/51#issuecomment-384919989>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ARvsZcGjtIcn8pdjSU7GQlExm88qLH1Bks5tsucigaJpZM4TQm8B>
> .
>

2018-04-28 08:10 UTC, 1mn commented
that's okay, @schwartzadev. We took care of this ourselves. See you around!