Move subdomains to query paths.
python-discord/site pull request #526
Opened 2021-06-07 22:36 UTC by jchristgit

In more detail:

- Use Django URL namespaces (e.g. `api:bot:infractions`) instead of
  `django_hosts` host argument.
- Update the hosts file setup documentation to remove subdomain entries.
- Update the hosts file setup documentation to mention that the entry of
  `pythondiscord.local` is not required and mainly for convenience.
- Rename the `APISubdomainTestCase` to the more fitting
  `AuthenticatedAPITestCase`, as authentication is all that is left that the
  class is doing.
- Drop dependency to `django_hosts`.

Closes #391.

2021-06-08 06:50 UTC, lemonsaurus approved these changes
A simple and straight forward change, looks like the right idea. I don't comb through every single line of code but if tests are passing and manual testing looks good, this seems fine to me.

2021-08-31 00:19 UTC, jb3 approved these changes

2021-08-31 00:28 UTC, jb3 requested changes
We might need further modification to support internal routing through NGINX, will coordinate on Discord.

2021-08-31 19:57 UTC, jchristgit commented
Thanks, Joe.

2021-10-06 21:34 UTC, jb3 approved these changes

2021-10-06 21:38 UTC, merged