Fix data reviews URL
python-discord/site pull request #565
Opened 2021-08-12 19:08 UTC by ethansocal

I updated the URL on the timeline for data reviews from `https://pythondiscord.com/pages/data-reviews/` to `https://www.notion.so/6784e3a9752444e89d19e65fd4510d8d?v=69268794b9d2454a9c28e1550e2923c2`.

2021-08-12 19:09 UTC, ethansocal commented
Resolves #564

2021-08-12 20:07 UTC, Akarys42 requested changes, later dismissed
Hey @ethansocal, thanks a lot for the PR! After internal discussions, we decided to instead use the `notion.site` link to avoid domain blocks. Sorry 😅

Feel free to apply directly from GitHub or from your computer!

2021-08-12 20:07 UTC, Akarys42 commented on pydis_site/templates/home/timeline.html
> +                href="https://www.notion.so/6784e3a9752444e89d19e65fd4510d8d?v=69268794b9d2454a9c28e1550e2923c2">monthly data reviews</a>.</p>
```suggestion
                href="https://pythondiscord.notion.site/6784e3a9752444e89d19e65fd4510d8d">monthly data reviews</a>.</p>
```

2021-08-12 20:33 UTC, wookie184 approved these changes
Thanks!

2021-08-12 21:47 UTC, Bluenix2 approved these changes
Great! Thank you for your contribution

2021-08-25 14:58 UTC, Akarys42 approved these changes
Perfect, thank you!

2021-08-25 14:58 UTC, merged