documentation metadata API
python-discord/site pull request #57
Opened 2018-04-24 17:17 UTC by jchristgit

This PR implements the API endpoints to accompany https://github.com/discord-python/bot/pull/53.
In a nutshell, it

- adds a new database "schema" for storing documentation metadata
- adds api endpoints for modifying this metadata
- adds tests for the above.

This way, documentation metadata used for the documentation lookup cog will be stored in the site's database and can easily be changed through (to be implemented-) bot commands.

2018-04-26 11:52 UTC, gdude2002 requested changes

2018-04-26 11:52 UTC, gdude2002 commented on pysite/views/api/bot/doc.py
> +            package = params[0].get("package")
This schema setup is intended to allow one to specify multiple sets of parameters. You should support this in your endpoints.

2018-04-26 11:52 UTC, gdude2002 commented on pysite/views/api/bot/doc.py
> +        json_data = json_data[0]
This schema setup is intended to allow one to specify multiple sets of parameters. You should support this in your endpoints.

2018-04-26 11:52 UTC, gdude2002 commented on pysite/views/api/bot/doc.py
> +        package = json_data[0]["package"]
This schema setup is intended to allow one to specify multiple sets of parameters. You should support this in your endpoints.

2018-04-27 10:19 UTC, gdude2002 submitted a review, later dismissed

2018-04-27 10:19 UTC, gdude2002 commented on pysite/views/api/bot/doc.py
> +            for json_object in json_data
I think I'd prefer this line to be moved up, after the `}`

2018-04-27 11:13 UTC, lemonsaurus submitted a review, later dismissed
This is just a really excellent PR.

2018-05-20 16:04 UTC, gdude2002 submitted a review, later dismissed

2018-06-05 13:14 UTC, gdude2002 approved these changes

2018-06-05 13:14 UTC, merged