Add Django Prometheus
python-discord/site pull request #575
Opened 2021-09-02 21:18 UTC by jb3

Adds Django Prometheus and installs the necessary middleware and URL paths for reporting.

2021-09-02 21:59 UTC, doublevcodes requested changes

2021-09-02 21:59 UTC, doublevcodes commented on pyproject.toml
> +django-prometheus = "^2.1.0"
```suggestion
django-prometheus = "~=2.1"
```
This should be changed to follow the format of the other pinned dependencies.

2021-09-02 22:07 UTC, doublevcodes approved these changes
LGTM now :shipit:

2021-09-02 23:48 UTC, Den4200 approved these changes

2021-09-03 16:58 UTC, jchristgit requested changes
Yes, but also no.

This is nice. This needs a change though, because we are using multiple workers, because Python can't gobble around on more than one core in the same address space.

`gunicorn` needs to be started with a configuration file as its argument, with the following contents:
```py
from prometheus_client import multiprocess

def child_exit(server, worker):
    multiprocess.mark_process_dead(worker.pid)
```

This is step three from the Prometheus Python client's multiprocess mode considerations: https://github.com/prometheus/client_python. Step two is [taken care of](https://github.com/korfuri/django-prometheus/blob/434a3ba36bdada45c9633451f5f6cfd145814ccf/django_prometheus/exports.py#L119) by `django-prometheus`, step one I will PR into the Kubernetes repository.

2021-09-03 16:59 UTC, jchristgit commented
And as a small bonus, it would be nice if you could add a small comment in the `Dockerfile` explaining why we need `BUILDING_DOCKER=yes`.

2021-09-04 09:04 UTC, merged

2021-09-04 18:02 UTC, jchristgit reviewed
Solid. Thanks!