Add guide for working with Python on Windows
python-discord/site pull request #773
Opened 2022-09-25 16:02 UTC by wookie184

This is an incomplete draft.

Not sure whether this would be better split up into different pages.

2022-10-21 15:02 UTC, wookie184 commented
This still isn't quite finished, but it'd be good to get some reviews on the content. Please leave a comment if you think there's anything that should be added (you can take a look at the linked issues for ideas).

2022-10-21 15:23 UTC, mbaruh commented
Thanks for this! A few immediate comments:

- Should we maybe have a subdirectory for all of this? an issue might encompass several of those articles, and they're relativeley scattered in the currently resulting list of guides..
- Is "Don't use the py installer" a stance we want to take? I'm not a fan of it myself, but maybe it would be wiser to have a general page about it, with a section about caveats to watch out for.
- In the PATH section, I think it's worth noting that if it contains several Python versions, using `python` in a terminal will invoke the top one.

2022-10-21 16:06 UTC, wookie184 commented
>     * Should we maybe have a subdirectory for all of this? an issue might encompass several of those articles, and they're relatively scattered in the currently resulting list of guides..

Yeah, that would probably make sense

>     * Is "Don't use the py installer" a stance we want to take? I'm not a fan of it myself, but maybe it would be wiser to have a general page about it, with a section about caveats to watch out for.

WDYM by "py installer"?
>     * In the PATH section, I think it's worth noting that if it contains several Python versions, using `python` in a terminal will invoke the top\first one.

I mention that here https://deploy-preview-773--pydis-static.netlify.app/pages/guides/python-guides/python-on-windows/#the-advanced-method-editing-environment-variables, although maybe it should be moved to another point on that page or made more obvious?
> You should now see a list of paths. Each path represents a folder that will be
searched for executables when looking up a command name in the terminal. The
paths are searched from top to bottom, and the first executable found matching
the name will be used. The system PATH variable has priority over the user one.

2022-10-21 16:47 UTC, mbaruh commented
> WDYM by "py installer"?

Oh sorry I meant the microsoft store page.

> maybe it should be moved to another point on that page or made more obvious?

Ah I missed that. yeah maybe it should be in the form of "this is what you need to make sure of to make it work"

2022-10-21 16:52 UTC, wookie184 commented
> > WDYM by "py installer"?
> 
> Oh sorry I meant the microsoft store page.

Well, I don't think we should recommend that people use it (due to said caveats), so i'm not sure what else would be on such a page (maybe how to uninstall it lol).
> > maybe it should be moved to another point on that page or made more obvious?
>
> Ah I missed that. yeah maybe it should be in the form of "this is what you need to make sure of to make it work"

👍

2022-11-15 16:26 UTC, shtlrs commented
I think #794 now has all the content of your PR combined there, isn't it ?  Should we just keep one PR then ?

2022-11-15 21:49 UTC, discretegames commented
> I think #794 now has all the content of your PR combined there, isn't it ? Should we just keep one PR then ?

I'm for that. I think #794 is ready to be merged into here (or however that works exactly) if wookie signs off on it. 

The "TODO: Add more screenshots" is done, and #794 has articles that could be linked from most of the proposed !install, !windows-path, etc. tags (to supplement, not replace the tags).

2023-03-22 18:06 UTC, MrHemlock requested changes
Very well done.  The main bulk of my gripes is the underselling of the `py` launcher.  I feel like that should be the way we tell new users to use Python on Windows.  Especially if people plan on having multiple different versions of Python on their rig.

2023-03-22 18:06 UTC, MrHemlock commented on pydis_site/apps/content/resources/guides/python-guides/windows/common-issues.md
> +with `py`. See [this guide](../installing-and-using-python/#the-py-launcher) for more information on that.
I would say that using the `py` launcher should be the first recommendation.  Managing the aliases isn't necessary if you stick with using it.  I'd say change the section a little where using `py` is the default recommendation, and another header saying "If you still want to using `python` instead of `py`

2023-03-22 18:06 UTC, MrHemlock commented on pydis_site/apps/content/resources/guides/python-guides/windows/common-issues.md
> +with `py`. See [this guide](../installing-and-using-python/#the-py-launcher) for more information on that.
We should probably also address here or below how to install using `py` by doing `py -m pip install [package_name_here]`.

2023-03-22 18:06 UTC, MrHemlock commented on pydis_site/apps/content/resources/guides/python-guides/windows/common-issues.md
> +### I `pip` installed a package but when running my code I get a `ModuleNotFoundError`
As above, the usage of `py -m pip install` can be both helpful and important.  If there is an issue with the PATH or other factors, `python` and `pip` may point to different versions.  Using `py -m pip install` guarantees that whatever you pip install will go into that `py` version.

2023-03-22 18:06 UTC, MrHemlock commented on pydis_site/apps/content/resources/guides/python-guides/windows/common-issues.md
> +### I `pip` installed a command line program but it isn't recognized
Again, `py` launcher can help rectify some of this, including running some even when `\Scripts` isn't in the path.  For example if you `py -m pip install black`, then try to just do `black` it may not work.  But if you do `py -m black` it should.

2023-03-22 18:06 UTC, MrHemlock commented on pydis_site/apps/content/resources/guides/python-guides/windows/common-issues.md
> +When you type `python` in the terminal you enter into the python REPL ([read-evaluate-print
```suggestion
When you type `python` or `py` in the terminal you enter into the python REPL ([read-evaluate-print
```

2023-03-22 18:06 UTC, MrHemlock commented on pydis_site/apps/content/resources/guides/python-guides/windows/common-issues.md
> +General commands like `pip` and `python` should be run in your computer's normal terminal, that is, directly in
```suggestion
General commands like `py`, `pip` and `python` should be run in your computer's normal terminal, that is, directly in
```

2023-03-22 18:06 UTC, MrHemlock commented on pydis_site/apps/content/resources/guides/python-guides/windows/installing-and-using-python.md
> +except making sure to check the "Add python.exe to PATH" checkbox. Getting Python from the [Microsoft
I would highly recommend NOT adding python to PATH.  The `py` launcher handles most if not all of that pathing.  This will also prevent potential issues if you have multiple different versions of Python installed on your machine.

2023-03-22 18:06 UTC, MrHemlock commented on pydis_site/apps/content/resources/guides/python-guides/windows/installing-and-using-python.md
> +    guide](../putting-python-on-path) to learn more.)
As above, I recommend not adding to PATH.

2023-03-22 18:06 UTC, MrHemlock commented on pydis_site/apps/content/resources/guides/python-guides/windows/installing-and-using-python.md
> +Or try the more usual way of running Python by typing `python` in a new terminal window to open up the Python
```suggestion
Or try the more usual way of running Python by typing `py` or `python` in a new terminal window to open up the Python
```

2023-03-22 18:06 UTC, MrHemlock commented on pydis_site/apps/content/resources/guides/python-guides/windows/installing-and-using-python.md
> +The `venv` module used above comes with Python, but [Poetry](https://python-poetry.org/),
Possibly add `pdm` to the list as that one has been growing in popularity. https://pdm.fming.dev/

2023-03-22 18:06 UTC, MrHemlock commented on pydis_site/apps/content/resources/guides/python-guides/windows/putting-python-on-path.md
> +---
I would add a huge caveat about this section.  Adding to PATH is not necessary when using the `py` launcher, and really shouldn't need to be done unless you just want to or you have a particular reason.

2023-04-07 18:06 UTC, wookie184 commented on pydis_site/apps/content/resources/guides/python-guides/windows/common-issues.md
> +### I `pip` installed a command line program but it isn't recognized
This works well for some tools, but not others. For example, with pyinstaller you have to run `py -m PyInstaller` with that exact capitalisation - something that I don't believe is clearly documented anywhere, the docs just say to use `pyinstaller` directly so it's confusing when that doesn't work. There are also other tools that don't have any `-m` alternative that i've been able to find, like https://csvkit.readthedocs.io/en/latest/.

The `py` installer is nice, but it requires a certain amount of knowledge to know when and how to convert commands given in documentation to work with `py`. I think users generally want to be able to run commands in the way that docs give them.

It's annoying that stuff like this is such a minefield, there are a bunch of ways to make things work using just the `py` launcher - like by using pipx for tools and virtual environments when you want to just be able to `python`, but I wanted to try and keep this guide fairly simple.

2023-07-24 14:50 UTC, jchristgit commented
Hi everyone, is there a way to help out with getting this pull request merged?

2023-12-09 08:21 UTC, jchristgit commented
Hi @wookie184. Did you find some time to look at the review comments, or is this up for grabs?

2024-05-20 19:13 UTC, wookie184 commented
If we can make a decision on whether to guide the user to have `python` on their PATH, or just to have them use `py`, it would help to move this forwards.

I prefer getting the user to have `python` on ther PATH for the reasons I mention here https://github.com/python-discord/site/pull/773#discussion_r1160869869, so personally I'm quite happy with leaving the PR mostly as is, though I could make some of the changes to make `py` a bit more visible as an option.

2024-06-20 15:25 UTC, jchristgit commented
> I prefer getting the user to have python on ther PATH for the reasons I mention here https://github.com/python-discord/site/pull/773#discussion_r1160869869, so personally I'm quite happy with leaving the PR mostly as is, though I could make some of the changes to make py a bit more visible as an option.

I can't really comment on this as I do not run Python on Windows but your reasoning makes sense to me, and we should leave it mostly as is.

2025-02-06 19:45 UTC, jchristgit commented
@wookie184 good morning and happy new year! I hope you've had a great start to the year so far.

I'm wondering if there's something I can do to help move this PR forward?

2025-09-15 21:40 UTC, wookie184 commented
With the introduction of PEP 773 and uv this is pretty outdated and I'm not interested in working on it, so I'll close this.

2025-09-15 21:40 UTC, closed without merging